=== nehasai/nehas/target/classes/definitions/Practitioner.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "identifier": {
      "type": "object",
      "properties": {
        "portalId": {
          "type": "string"
        },
        "npi": {
          "type": "string"
        }
      },
      "required": [
        "portalId"
      ]
    },
    "name": {
      "type": "object",
      "properties": {
        "first": {
          "type": "string"
        },
        "last": {
          "type": "string"
        }
      },
      "required": [
        "first",
        "last"
      ]
    },
    "role": {
      "type": "object",
      "properties": {
        "managingOrganization": {
          "type": "object",
          "properties": {
            "identifier": {
              "type": "object",
              "properties": {
                "npi": {
                  "type": "string"
                },
                "portalId": {
                  "type": "string"
                }
              },
              "required": [
                "portalId"
              ]
            }
          },
          "required": [
            "identifier"
          ]
        },
        "specialty": {
          "type": "string"
        }
      },
      "required": [
        "managingOrganization"
      ]
    },
    "address": {
      "type": "object",
      "properties": {
        "line": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "zip": {
          "type": "string"
        }
      },
      "required": [
        "line",
        "city",
        "country",
        "state",
        "zip"
      ]
    },
    "telecom": {
      "type": "object",
      "properties": {
        "fax": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        }
      },
      "required": [
        "fax",
        "phone"
      ]
    },
    "registeredByIdentifier": {
      "type": "object",
      "properties": {
        "portalId": {
          "type": "string"
        }
      },
      "required": [
        "portalId"
      ]
    }
  },
  "required": [
    "identifier",
    "name",
    "role",
    "address",
    "telecom",
    "registeredByIdentifier"
  ]
}

=== nehasai/nehas/src/main/resources/api/examples/post_practitioner_request.json
{
  "identifier": {
    "portalId": "liferay456",
    "npi": "npi456"
  },
  "name": {
    "first": "Adam",
    "last": "Careful"
  },
  "role": {
    "managingOrganization": {
      "identifier": {
        "npi": "npi123",
        "portalId": "liferay123"
      }
    },
    "specialty": "Gastroenterology"
  },
  "address": {
    "line": [
      "Address Line1",
      "Address Line2",
      "Address Line3"
    ],
    "city": "San Diego",
    "country": "US",
    "state": "California",
    "zip": "12345"
  },
  "telecom": {
    "fax": "0123456789",
    "phone": "1234567890"
  },
  "registeredByIdentifier": {
    "portalId": "somePortalUserId"
  }
}
